language: node_js

node_js:
  - "6"
  
cache:
  directories:
    - node_modules
    
before_install:
  - 'npm i -g npm@latest'
  
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
  - 'bash <(curl -s https://codecov.io/bash)'
